#!/bin/python3
#This was made in June 2024 by Leo Platti to practice my app developing skills by making a useful application that can be used to calculate intake of important daily nutrients
#My goal is to develop a working calculator for said purposes then go through and add a gui to it for ease of access!
import os
import python3
import math
print("-"*70)
print("Welcome to Calorie Calc, the app for all of your nutritious needs")
input = input("[1] Meal Calculator, [2] Portion Calculator, [3] Drink Calculator").strip.lower

def meal_calc
    ingredient_num = input("Enter number of ingredients to be input: ")
    for i in ingredient_num
    

def portion_calc
    name = input("Enter name of portion to be calculated: ")
    calories = input(int("Enter calories"))
    fat = input(int("Enter fat (grams): ")).strip
    cholesterol = input(int("Enter cholesterol (grams): ")).strip
    sodium = input(int("Enter sodium (grams): ")).strip
    total_carbs = input(int("Enter carbs (grams): ")).strip
    fiber = input(int("Enter fiber (grams): ")).strip
    sugar = input(int("Enter sugar (grams): ")).strip
    protein = input(int("Enter protein (grams): ")).strip
    servings = input(int("Enter number of servings to be calculated: ")).strip

def drink_calc
    name = input("Enter name of beverage to be calculated: ")
    sugars = input(int("Enter sugar (grams): ")).strip
    sodium = input(int("Enter sodium (grams): ")).strip
    carbohydrate = input(int("Enter Carbohydrates (grams): ")).strip
    protein = input(int("Enter protein (grams): ")).strip
    servings = input(int("Enter number of servings to be calculated: ")).strip

def main:
if input = "1":
    meal_calc
if input = "2":
    portion_calc
if input = "3":
    drink_calc
else:
    print("Invalid input please retry (1-3)")
    main()
main()
